<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DAL12_JSON\DALJSON.csproj" />
    <ProjectReference Include="..\lab01\DAL.csproj" />
  </ItemGroup>

</Project>
