CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(200) NOT NULL,
    ContactPerson VARCHAR2(100),
    Phone VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE,
    Address VARCHAR2(255),
    RegistrationDate DATE DEFAULT SYSDATE
);

CREATE TABLE Employees (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName VARCHAR2(100) NOT NULL,
    Position VARCHAR2(100),
    Phone VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE,
    HireDate DATE NOT NULL
);

CREATE TABLE ServiceCategories (
    CategoryID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryName VARCHAR2(100) NOT NULL,
    Description VARCHAR2(255)
);

CREATE TABLE Services (
    ServiceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ServiceName VARCHAR2(200) NOT NULL,
    Description VARCHAR2(500),
    DefaultPrice NUMBER(10,2) NOT NULL,
    Unit VARCHAR2(50),
    CategoryID NUMBER REFERENCES ServiceCategories(CategoryID)
);

CREATE TABLE OrderStatuses (
    StatusID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StatusName VARCHAR2(50) NOT NULL,
    Description VARCHAR2(255)
);

CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER NOT NULL REFERENCES Customers(CustomerID),
    OrderDate DATE DEFAULT SYSDATE,
    RequiredDate DATE,
    StatusID NUMBER NOT NULL REFERENCES OrderStatuses(StatusID),
    TotalAmount NUMBER(12,2),
    Notes CLOB,
    CreatedBy NUMBER REFERENCES Employees(EmployeeID)
);

CREATE TABLE OrderItems (
    OrderItemID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL REFERENCES Orders(OrderID),
    ServiceID NUMBER NOT NULL REFERENCES Services(ServiceID),
    Quantity NUMBER(10,2) NOT NULL,
    UnitPrice NUMBER(10,2) NOT NULL,
    Discount NUMBER(5,2) DEFAULT 0,
    Amount NUMBER GENERATED ALWAYS AS (Quantity * UnitPrice * (1 - Discount/100)) VIRTUAL
);

CREATE TABLE Materials (
    MaterialID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaterialName VARCHAR2(200) NOT NULL,
    Unit VARCHAR2(50),
    CurrentStock NUMBER(10,2)
);

CREATE TABLE OrderMaterials (
    OrderID NUMBER NOT NULL REFERENCES Orders(OrderID),
    MaterialID NUMBER NOT NULL REFERENCES Materials(MaterialID),
    QuantityUsed NUMBER(10,2) NOT NULL,
    UnitCost NUMBER(10,2),
    PRIMARY KEY (OrderID, MaterialID)
);

CREATE TABLE Invoices (
    InvoiceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL REFERENCES Orders(OrderID),
    InvoiceDate DATE DEFAULT SYSDATE,
    DueDate DATE,
    TotalAmount NUMBER(12,2) NOT NULL,
    PaidAmount NUMBER(12,2) DEFAULT 0,
    Status VARCHAR2(20) DEFAULT 'Unpaid' CHECK (Status IN ('Unpaid', 'Partial', 'Paid'))
);

CREATE TABLE Payments (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    InvoiceID NUMBER NOT NULL REFERENCES Invoices(InvoiceID),
    PaymentDate DATE DEFAULT SYSDATE,
    Amount NUMBER(12,2) NOT NULL,
    PaymentMethod VARCHAR2(50)
);

CREATE TABLE Timesheets (
    TimesheetID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderItemID NUMBER NOT NULL REFERENCES OrderItems(OrderItemID),
    EmployeeID NUMBER NOT NULL REFERENCES Employees(EmployeeID),
    WorkDate DATE NOT NULL,
    HoursWorked NUMBER(5,2) NOT NULL
);

CREATE INDEX IX_Orders_CustomerID ON Orders(CustomerID);
CREATE INDEX IX_Orders_StatusID ON Orders(StatusID);
CREATE INDEX IX_OrderItems_OrderID ON OrderItems(OrderID);
CREATE INDEX IX_OrderItems_ServiceID ON OrderItems(ServiceID);
CREATE INDEX IX_Invoices_OrderID ON Invoices(OrderID);
CREATE INDEX IX_Payments_InvoiceID ON Payments(InvoiceID);
CREATE INDEX IX_Timesheets_EmployeeID ON Timesheets(EmployeeID);
CREATE INDEX IX_Timesheets_OrderItemID ON Timesheets(OrderItemID);

CREATE OR REPLACE VIEW vw_ActiveOrders AS
SELECT 
    o.OrderID,
    c.Name AS CustomerName,
    o.OrderDate,
    o.RequiredDate,
    os.StatusName,
    o.TotalAmount,
    (o.RequiredDate - o.OrderDate) AS DaysToComplete
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN OrderStatuses os ON o.StatusID = os.StatusID
WHERE os.StatusName != 'Completed' 
  AND os.StatusName != 'Cancelled';

CREATE OR REPLACE FUNCTION fn_CalculateOrderTotal(
    p_OrderID IN NUMBER
) RETURN NUMBER
IS
    v_Total NUMBER(12,2);
BEGIN
    SELECT NVL(SUM(Amount), 0)
    INTO v_Total
    FROM OrderItems
    WHERE OrderID = p_OrderID;
    
    RETURN v_Total;
END fn_CalculateOrderTotal;

CREATE OR REPLACE FUNCTION fn_GetInvoiceStatus(
    p_InvoiceID IN NUMBER
) RETURN VARCHAR2
IS
    v_Status VARCHAR2(20);
    v_Total NUMBER(12,2);
    v_Paid NUMBER(12,2);
BEGIN
    SELECT TotalAmount, PaidAmount
    INTO v_Total, v_Paid
    FROM Invoices
    WHERE InvoiceID = p_InvoiceID;
    
    IF v_Paid >= v_Total THEN
        v_Status := 'Paid';
    ELSIF v_Paid > 0 THEN
        v_Status := 'Partial';
    ELSE
        v_Status := 'Unpaid';
    END IF;
    
    RETURN v_Status;
END fn_GetInvoiceStatus;

CREATE OR REPLACE PROCEDURE sp_CreateOrder(
    p_CustomerID IN NUMBER,
    p_RequiredDate IN DATE,
    p_StatusID IN NUMBER,
    p_CreatedBy IN NUMBER,
    p_Notes IN CLOB DEFAULT NULL,
    p_OrderID OUT NUMBER
)
IS
BEGIN
    SAVEPOINT sp_CreateOrder;
    
    INSERT INTO Orders (CustomerID, RequiredDate, StatusID, CreatedBy, Notes)
    VALUES (p_CustomerID, p_RequiredDate, p_StatusID, p_CreatedBy, p_Notes)
    RETURNING OrderID INTO p_OrderID;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO sp_CreateOrder;
        RAISE;
END sp_CreateOrder;

CREATE OR REPLACE PROCEDURE sp_AddOrderItem(
    p_OrderID IN NUMBER,
    p_ServiceID IN NUMBER,
    p_Quantity IN NUMBER,
    p_UnitPrice IN NUMBER DEFAULT NULL,
    p_Discount IN NUMBER DEFAULT 0
)
IS
    v_UnitPrice NUMBER(10,2);
BEGIN
    SAVEPOINT sp_AddOrderItem;
    
    IF p_UnitPrice IS NULL THEN
        SELECT DefaultPrice INTO v_UnitPrice
        FROM Services
        WHERE ServiceID = p_ServiceID;
    ELSE
        v_UnitPrice := p_UnitPrice;
    END IF;
    
    INSERT INTO OrderItems (OrderID, ServiceID, Quantity, UnitPrice, Discount)
    VALUES (p_OrderID, p_ServiceID, p_Quantity, v_UnitPrice, p_Discount);
    
    UPDATE Orders
    SET TotalAmount = fn_CalculateOrderTotal(p_OrderID)
    WHERE OrderID = p_OrderID;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO sp_AddOrderItem;
        RAISE;
END sp_AddOrderItem;

CREATE OR REPLACE PROCEDURE sp_RegisterPayment(
    p_InvoiceID IN NUMBER,
    p_Amount IN NUMBER,
    p_PaymentMethod IN VARCHAR2,
    p_PaymentID OUT NUMBER
)
IS
    v_Remaining NUMBER(12,2);
BEGIN
    SAVEPOINT sp_RegisterPayment;
    
    SELECT TotalAmount - PaidAmount INTO v_Remaining
    FROM Invoices
    WHERE InvoiceID = p_InvoiceID
    FOR UPDATE;
    
    IF p_Amount > v_Remaining THEN
        RAISE_APPLICATION_ERROR(-20001, 'Payment amount exceeds remaining balance');
    END IF;
    
    INSERT INTO Payments (InvoiceID, Amount, PaymentMethod)
    VALUES (p_InvoiceID, p_Amount, p_PaymentMethod)
    RETURNING PaymentID INTO p_PaymentID;
    
    UPDATE Invoices
    SET 
        PaidAmount = PaidAmount + p_Amount,
        Status = fn_GetInvoiceStatus(InvoiceID)
    WHERE InvoiceID = p_InvoiceID;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO sp_RegisterPayment;
        RAISE;
END sp_RegisterPayment;

CREATE OR REPLACE PROCEDURE sp_ConsumeMaterials(
    p_OrderID IN NUMBER,
    p_MaterialID IN NUMBER,
    p_QuantityUsed IN NUMBER,
    p_UnitCost IN NUMBER DEFAULT NULL
)
IS
    v_CurrentStock NUMBER(10,2);
    v_AvgCost NUMBER(10,2);
BEGIN
    SAVEPOINT sp_ConsumeMaterials;
    
    SELECT CurrentStock INTO v_CurrentStock
    FROM Materials
    WHERE MaterialID = p_MaterialID
    FOR UPDATE;
    
    IF v_CurrentStock < p_QuantityUsed THEN
        RAISE_APPLICATION_ERROR(-20002, 'Insufficient materials in stock');
    END IF;
    
    IF p_UnitCost IS NULL THEN
        SELECT NVL(AVG(UnitCost), 0) INTO v_AvgCost
        FROM OrderMaterials
        WHERE MaterialID = p_MaterialID;
        
        IF v_AvgCost = 0 THEN
            v_AvgCost := 0;
        END IF;
    ELSE
        v_AvgCost := p_UnitCost;
    END IF;
    
    INSERT INTO OrderMaterials (OrderID, MaterialID, QuantityUsed, UnitCost)
    VALUES (p_OrderID, p_MaterialID, p_QuantityUsed, v_AvgCost);
    
    UPDATE Materials
    SET CurrentStock = CurrentStock - p_QuantityUsed
    WHERE MaterialID = p_MaterialID;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO sp_ConsumeMaterials;
        RAISE;
END sp_ConsumeMaterials;

CREATE OR REPLACE PROCEDURE sp_CreateInvoice(
    p_OrderID IN NUMBER,
    p_DueDate IN DATE DEFAULT NULL,
    p_InvoiceID OUT NUMBER
)
IS
    v_TotalAmount NUMBER(12,2);
    v_DueDate DATE;
BEGIN
    SAVEPOINT sp_CreateInvoice;
    
    SELECT TotalAmount INTO v_TotalAmount
    FROM Orders
    WHERE OrderID = p_OrderID;
    
    v_DueDate := NVL(p_DueDate, SYSDATE + 14);
    
    INSERT INTO Invoices (OrderID, DueDate, TotalAmount)
    VALUES (p_OrderID, v_DueDate, v_TotalAmount)
    RETURNING InvoiceID INTO p_InvoiceID;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO sp_CreateInvoice;
        RAISE;
END sp_CreateInvoice;

CREATE OR REPLACE PROCEDURE sp_AddTimesheetEntry(
    p_OrderItemID IN NUMBER,
    p_EmployeeID IN NUMBER,
    p_WorkDate IN DATE,
    p_HoursWorked IN NUMBER
)
IS
    v_TotalHours NUMBER(5,2);
BEGIN
    SELECT NVL(SUM(HoursWorked), 0) INTO v_TotalHours
    FROM Timesheets
    WHERE EmployeeID = p_EmployeeID 
      AND TRUNC(WorkDate) = TRUNC(p_WorkDate);
    
    IF v_TotalHours + p_HoursWorked > 24 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Employee cannot work more than 24 hours per day');
    END IF;
    
    INSERT INTO Timesheets (OrderItemID, EmployeeID, WorkDate, HoursWorked)
    VALUES (p_OrderItemID, p_EmployeeID, p_WorkDate, p_HoursWorked);
    
    COMMIT;
END sp_AddTimesheetEntry;

CREATE OR REPLACE TRIGGER tr_OrderItems_UpdateTotal
AFTER INSERT OR UPDATE OR DELETE ON OrderItems
FOR EACH ROW
DECLARE
    v_OrderID NUMBER;
BEGIN
    IF INSERTING OR UPDATING THEN
        v_OrderID := :NEW.OrderID;
    ELSIF DELETING THEN
        v_OrderID := :OLD.OrderID;
    END IF;
    
    UPDATE Orders
    SET TotalAmount = fn_CalculateOrderTotal(v_OrderID)
    WHERE OrderID = v_OrderID;
END tr_OrderItems_UpdateTotal;

CREATE OR REPLACE TRIGGER tr_Orders_CheckDates
BEFORE INSERT OR UPDATE ON Orders
FOR EACH ROW
BEGIN
    IF :NEW.RequiredDate < :NEW.OrderDate THEN
        RAISE_APPLICATION_ERROR(-20004, 'Required date cannot be earlier than order date');
    END IF;
END tr_Orders_CheckDates;