--1
SELECT TABLESPACE_NAME, CONTENTS, STATUS
FROM DBA_TABLESPACES;

--2
SELECT FILE_ID, FILE_NAME, TABLESPACE_NAME, BYTES, STATUS
FROM DBA_DATA_FILES
UNION ALL
SELECT FILE_ID, FILE_NAME, TABLESPACE_NAME, BYTES, STATUS
FROM DBA_TEMP_FILES;

--3
SELECT GROUP#, THREAD#, SEQUENCE#, MEMBERS, STATUS, ARCHIVED 
FROM V$LOG;

--4
SELECT GROUP#, MEMBER, TYPE, IS_RECOVERY_DEST_FILE, STATUS 
FROM V$LOGFILE;

--5
SELECT GROUP#, THREAD#, SEQUENCE#, STATUS, FIRST_CHANGE# 
FROM V$LOG 
ORDER BY GROUP#;

ALTER SYSTEM SWITCH LOGFILE;

--6
ALTER DATABASE ADD LOGFILE GROUP 4 
    ('D:\database-orac\oradata\redo4_1.log',
     'D:\database-orac\oradata\redo4_2.log',
     'D:\database-orac\oradata\redo4_3.log') 
    SIZE 50M;

SELECT GROUP#, THREAD#, SEQUENCE#, STATUS, FIRST_CHANGE# 
FROM V$LOG 
ORDER BY GROUP#;

ALTER SYSTEM SWITCH LOGFILE;

--7
ALTER SYSTEM CHECKPOINT;

ALTER DATABASE DROP LOGFILE GROUP 4;

SELECT GROUP#, THREAD#, SEQUENCE#, STATUS, FIRST_CHANGE# 
FROM V$LOG 
ORDER BY GROUP#;

--8
SELECT LOG_MODE FROM V$DATABASE;

--9
SELECT SEQUENCE#, NAME 
FROM V$ARCHIVED_LOG
ORDER BY SEQUENCE# DESC
FETCH FIRST 1 ROWS ONLY;

--10 
-- SQL PLUS    sqlplus / as sysdba
-- SQL PLUS    SHUTDOWN IMMEDIATE;
-- SQL PLUS    STARTUP MOUNT;
-- SQL PLUS    ALTER DATABASE ARCHIVELOG;
-- SQL PLUS    ALTER DATABASE OPEN;


SELECT LOG_MODE FROM V$DATABASE;

--11
ALTER SYSTEM SWITCH LOGFILE;

SELECT SEQUENCE#, NAME 
FROM V$ARCHIVED_LOG
ORDER BY SEQUENCE# DESC
FETCH FIRST 1 ROWS ONLY;

SELECT SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE#
FROM V$ARCHIVED_LOG
ORDER BY SEQUENCE# DESC;

--12
-- SQL PLUS    sqlplus / as sysdba
-- SQL PLUS    SHUTDOWN IMMEDIATE;
-- SQL PLUS    STARTUP MOUNT;
-- SQL PLUS    ALTER DATABASE NOARCHIVELOG;
-- SQL PLUS    ALTER DATABASE OPEN;

SELECT LOG_MODE FROM V$DATABASE;

--13
SELECT NAME FROM V$CONTROLFILE;

--14
-- CMD         rman target /
-- CMD         LIST INCARNATION OF DATABASE;
