CREATE TABLE HBA_t(
    ID NUMBER (3) NOT NULL,
    STROK VARCHAR2 (50),
    PRIMARY KEY (ID)
);

INSERT INTO HBA_t (ID, STROK) VALUES (1, 'Строка 1');
INSERT INTO HBA_t (ID, STROK) VALUES (2, 'Строка 2');
INSERT INTO HBA_t (ID, STROK) VALUES (3, 'Строка 3');
COMMIT;

UPDATE HBA_t SET STROK = 'Измененная строка 1' WHERE ID = 1;
UPDATE HBA_t SET STROK = 'Измененная строка 2' WHERE ID = 2;
COMMIT;

SELECT * FROM HBA_t WHERE ID > 1;
SELECT COUNT(*) FROM HBA_t;
SELECT MAX(ID) FROM HBA_t;
SELECT MIN(ID) FROM HBA_t;

DELETE FROM HBA_t WHERE ID = 1;
ROLLBACK;
SELECT * FROM HBA_t;

CREATE TABLE HBA_t_CHILD(
    CHILD_ID NUMBER(3) NOT NULL,
    CHILD_DATA VARCHAR2(50),
    PARENT_ID NUMBER(3) NOT NULL,
    CONSTRAINT FK_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES HBA_t (ID)
);

INSERT INTO HBA_t_CHILD (CHILD_ID, CHILD_DATA, PARENT_ID) VALUES (1, 'Данные 1', 1);
INSERT INTO HBA_t_CHILD (CHILD_ID, CHILD_DATA, PARENT_ID) VALUES (2, 'Данные 2', 2);
INSERT INTO HBA_t_CHILD (CHILD_ID, CHILD_DATA, PARENT_ID) VALUES (3, 'Данные 3', 3);

SELECT * FROM HBA_t
LEFT JOIN HBA_t_CHILD ON HBA_t.ID = HBA_t_CHILD.PARENT_ID;

SELECT * FROM HBA_t
INNER JOIN HBA_t_CHILD ON HBA_t.ID = HBA_t_CHILD.PARENT_ID;

DROP TABLE HBA_t_CHILD;

DROP TABLE HBA_t;
