### 
@hp=http://localhost:5204
@capi=/api/Celebrities
###


###  все знаменитости
###  celebrities.MapGet("/", 
GET {{hp}}{{capi}} 

### знаменитость по ID
### MapGet("/{id:int:min(1)}"
GET {{hp}}{{capi}}/7

### знаменитость  по ID события 
### MapGet("/Lifeevents/{id:int:min(1)}"
GET {{hp}}{{capi}}/Lifeevents/7

###  удалить знаменитость  по ID
###.MapDelete("/{id:int:min(1)}",
DELETE {{hp}}{{capi}}/4


###  добавить новую знаменитость 
###  MapPost("/",
POST {{hp}}{{capi}}
Content-Type:application/json

  {
    "fullName":    "Ершов Андрей",
    "nationality": "RU",
    "reqPhotoPath":"Ershov.jpg"
  }

###  изменить знаменитость по ID  
###  MapPut("/{id:int:min(1)}", 
PUT {{hp}}{{capi}}/13
Content-Type:application/json

 {
    "fullName":    "Ершов Андрей Петрович",
    "nationality": "RU",
    "reqPhotoPath":"Ershov.jpg"
  }


### получить файл фотографии по имени файла (fname)
### MapGet("/photo/{fname}"
GET {{hp}}{{capi}}/photo/Ershov.jpg


### 
@lapi=/api/Lifeevents
###

###  все события 
###  MapGet("/",
GET {{hp}}{{lapi}}



###  событие по ID
###  MapGet("/{id:int:min(1)}"
GET {{hp}}{{lapi}}/10


###  все события по ID знаменитости  
###  MapGet("/Celebrities/{id:int:min(1)}
GET {{hp}}{{lapi}}/Celebrities/3


###  удалить событие  по ID
###  MapDelete("/{id:int:min(1)}"
DELETE {{hp}}{{lapi}}/10



###  добавить новое событие 
###  MapPost("/", 
POST {{hp}}{{lapi}}
Content-Type:application/json

{
    "celebrityId": 13,
    "date": "1931-04-19T00:00:00",
    "description": "Дата рождения",
    "reqPhotoPath": null
 }

###  изменить событие по ID 
###  MapPut("/{id:int:min(1)}"
PUT {{hp}}{{lapi}}/24 
Content-Type:application/json

{
    "celebrityId": 13,
    "date": "1931-04-19T00:00:00",
    "description": "Дата рождения. Москва.",
    "reqPhotoPath": null
}




###