ALTER SESSION SET "_oracle_script" = TRUE;

-- 1
CREATE TABLESPACE TS_HBA 
DATAFILE 'D:\database-orac\oradata\TS_HBA.dbf' SIZE 7M 
AUTOEXTEND ON NEXT 5M MAXSIZE 30M;

-- 2
CREATE TEMPORARY TABLESPACE TS_HBA_TEMP 
TEMPFILE 'D:\database-orac\oradata\TS_HBA_TEMP.dbf' SIZE 5M 
AUTOEXTEND ON NEXT 3M MAXSIZE 20M
EXTENT MANAGEMENT LOCAL;

--3
SELECT TABLESPACE_NAME, STATUS, CONTENTS 
FROM DBA_TABLESPACES;

--4 
SELECT FILE_NAME, TABLESPACE_NAME, BYTES/1024/1024 AS SIZE_MB, AUTOEXTENSIBLE 
FROM DBA_DATA_FILES;

--5
CREATE ROLE C##RL_HBACORE;
GRANT CONNECT TO C##RL_HBACORE;
GRANT CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE TO C##RL_HBACORE;
GRANT CREATE VIEW, DROP ANY VIEW TO C##RL_HBACORE;
GRANT CREATE PROCEDURE, DROP ANY PROCEDURE TO C##RL_HBACORE;

--6
SELECT * FROM DBA_ROLES WHERE ROLE = 'C##RL_HBACORE';

--7 
SELECT * 
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'C##RL_HBACORE';

--8
CREATE PROFILE C##PF_HBACORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

--9
SELECT PROFILE FROM dba_profiles;

--10
SELECT * FROM dba_profiles WHERE PROFILE = 'C##PF_HBACORE';

--11
SELECT * FROM dba_profiles WHERE PROFILE = 'DEFAULT';

--12
    CREATE USER C##HBACORE
    
        DEFAULT TABLESPACE TS_HBA
        TEMPORARY TABLESPACE TS_HBA_TEMP
        PROFILE C##PF_HBACORE
        ACCOUNT UNLOCK;
        PASSWORD EXPIRE;
        GRANT CREATE SESSION TO C##HBACORE;
        
DROP USER C##HBACORE

--13 sqlplus
sqlplus sys as sysdba
ALTER USER C##HBACORE IDENTIFIED BY mynewpass;
EXIT;
sqlplus C##HBACORE/mynewpass

--15
CREATE TABLE HBA_T (
    ID INT PRIMARY KEY,
    Name VARCHAR(100),
    Location VARCHAR(100),
    Price INT
);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (1, 'Yacht Club A', 'Lake A', 150);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (2, 'Yacht Club B', 'Lake B', 200);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (3, 'Yacht Club C', 'Lake C', 250);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (4, 'Yacht Club D', 'Lake D', 300);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (5, 'Yacht Club E', 'Lake E', 350);

--16
GRANT C##RL_HBACORE TO C##HBACORE;
ALTER USER C##HBACORE QUOTA 2M ON TS_HBA;

--17
CREATE TABLE HBA_T (
    ID INT PRIMARY KEY,
    Name VARCHAR(100),
    Location VARCHAR(100),
    Price INT
);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (1, 'Yacht Club A', 'Lake A', 150);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (2, 'Yacht Club B', 'Lake B', 200);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (3, 'Yacht Club C', 'Lake C', 250);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (4, 'Yacht Club D', 'Lake D', 300);

INSERT INTO HBA_T (ID, Name, Location, Price) 
VALUES (5, 'Yacht Club E', 'Lake E', 350);

--18
ALTER TABLESPACE TS_HBA OFFLINE;

--19
SELECT * FROM HBA_T;

--20
ALTER TABLESPACE TS_HBA ONLINE;
SELECT * FROM HBA_T;
