--1,3
SELECT PDB_ID, PDB_NAME, STATUS
FROM CDB_PDBS;

--4 
CREATE TABLESPACE U2_HBA_PDB 
    DATAFILE 'D:\database-orac\oradata\U2_HBA_PDB.dbf' 
    SIZE 100M 
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE ROLE U1_HBA_PDB;

CREATE PROFILE U1_HBA_PDB LIMIT 
    SESSIONS_PER_USER 5 
    FAILED_LOGIN_ATTEMPTS 3 
    PASSWORD_LIFE_TIME 30;

CREATE USER USER_HBA_PDB IDENTIFIED BY mypassword
    DEFAULT TABLESPACE U2_HBA_PDB
    TEMPORARY TABLESPACE TEMP
    PROFILE U1_HBA_PDB;

GRANT CONNECT, RESOURCE TO USER_HBA_PDB;
GRANT RESTRICTED SESSION TO USER_HBA_PDB;
GRANT U1_HBA_PDB TO USER_HBA_PDB;

SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'USER_HBA_PDB';
SELECT ROLE FROM DBA_ROLES WHERE ROLE = 'U1_HBA_PDB';
SELECT PROFILE FROM DBA_PROFILES WHERE PROFILE = 'U1_HBA_PDB';
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'U2_HBA_PDB';
    
--5 
ALTER USER USER_HBA_PDB QUOTA 100M ON U2_HBA_PDB;

CREATE TABLE HBA_TABLE (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);

INSERT INTO HBA_TABLE (id, name) VALUES (1, 'Item1');
INSERT INTO HBA_TABLE (id, name) VALUES (2, 'Item2');
INSERT INTO HBA_TABLE (id, name) VALUES (3, 'Item3');

SELECT * FROM HBA_TABLE;

--6
SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES 
FROM DBA_DATA_FILES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES 
FROM DBA_TEMP_FILES;

SELECT ROLE FROM DBA_ROLES;

SELECT GRANTEE, PRIVILEGE, TABLE_NAME
FROM DBA_TAB_PRIVS
WHERE GRANTEE IN (SELECT ROLE FROM DBA_ROLES);

SELECT PROFILE, RESOURCE_NAME, LIMIT FROM DBA_PROFILES;

SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS;
SELECT GRANTEE FROM DBA_ROLE_PRIVS;

--7
CREATE USER C##HBA_CORE IDENTIFIED BY mypassword;
GRANT CONNECT, RESOURCE TO C##HBA_CORE;

ALTER SESSION SET CONTAINER = HBA_PDB;
GRANT CONNECT TO C##HBA_CORE;
GRANT RESTRICTED SESSION TO C##HBA_CORE;

--8
GRANT CREATE TABLE TO C##HBA_CORE;

--10
ALTER USER C##HBA_CORE QUOTA 100M ON USERS;

CREATE TABLE HBA_TABLE2 (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);

INSERT INTO HBA_TABLE2 (id, name) VALUES (10, 'Item10');
INSERT INTO HBA_TABLE2 (id, name) VALUES (20, 'Item20');
INSERT INTO HBA_TABLE2 (id, name) VALUES (30, 'Item30');

SELECT * FROM HBA_TABLE2;

--11
SELECT owner, object_name, object_type
FROM dba_objects
WHERE owner = 'C##HBA_CORE';

SELECT owner, object_name, object_type
FROM dba_objects
WHERE owner = 'USER_HBA_PDB';

--12
CREATE USER C##KNI_CORE IDENTIFIED BY Qweasd123Qaz;
GRANT CONNECT, RESOURCE TO C##KNI_CORE;
GRANT RESTRICTED SESSION TO C##KNI_CORE;

--13
SELECT SID, SERIAL#, USERNAME, OSUSER, MACHINE, PROGRAM, LOGON_TIME
FROM V$SESSION 
WHERE CON_ID = 1;






